create table tbl_corp_member
(
    id                               bigint unsigned auto_increment primary key comment '기업회원 ID',
    corp_member_login_id             varchar(255) not null unique comment '로그인 ID',
    corp_member_password             varchar(255) not null comment '비밀번호 (암호화)',
    corp_member_company_name         varchar(255) not null comment '기업명',
    corp_member_business_number      varchar(20)  not null unique comment '사업자등록번호',
    corp_member_ceo_name             varchar(100) comment '대표자명',
    corp_kind_id                     bigint unsigned comment '업종 대카테고리',
    corp_kind_small_id               bigint unsigned comment '업종 소카테고리',
    corp_member_company_type         varchar(255) comment '기업형태',
    corp_member_company_size         varchar(255) comment '기업규모',
    corp_member_establishment_date   date comment '설립일',
    corp_member_email                varchar(255) not null unique comment '이메일',
    corp_member_phone                varchar(255) comment '전화번호',
    corp_member_address              text comment '회사 주소',
    corp_member_address_detail       varchar(255) comment '상세주소',
    corp_member_zipcode              varchar(255) comment '우편번호',
    corp_member_website_url          varchar(255) comment '홈페이지 URL',
    corp_member_logo_file_name       varchar(255) comment '로고 이미지 파일명',
    corp_member_logo_file_path       varchar(255) comment '로고 이미지 경로',
    corp_member_logo_file_size       int comment '로고 이미지 크기 (byte)',
    corp_photo_file_name             varchar(255) comment '사진 파일명',
    corp_photo_file_path             varchar(255) comment '사진 경로',
    corp_photo_file_size             int comment '사진 크기 (byte)',
    corp_member_fax                  varchar(255) comment 'fax 번호',
    corp_member_capital_money_first  int comment '자본금 억',
    corp_member_capital_money_second int comment '자본금 만원',
    corp_member_total_sales          int comment '매출액',
    corp_performance                 text comment '연혁 및 실적',
    corp_vision                      text comment '개요 및 비전',
    corp_member_status               enum ('active', 'inactive') default 'active' comment '회원 상태',
    corp_member_agree_privacy        boolean                     default false comment '개인정보처리방침 동의',
    corp_member_created_at           datetime                    default current_timestamp comment '가입일',
    corp_member_updated_at           datetime                    default current_timestamp on update current_timestamp comment '수정일'
);